terraform {
  required_version = ">= 1.0"
}

# Local file resource that generates a file with dummy content
resource "local_file" "example" {
  filename = "${path.module}/generated/example.txt"
  content  = <<-EOT
    This is a dummy file generated by Terraform.
    
    This file demonstrates the preservation problem:
    - Created during Apply
    - Should be preserved for Verify Plan
    - Without preservation, Terraform will try to recreate it
    
    Sample data:
    - Name: Example File
    - Environment: Test
    - Purpose: Demonstrate file preservation
  EOT
  
  file_permission = "0644"
}

# Another local file with JSON content
resource "local_file" "config" {
  filename = "${path.module}/generated/config.json"
  content = jsonencode({
    application = "preserve-files-demo"
    version     = "1.0.0"
    environment = "test"
    features = [
      "tar-archive",
      "s3-upload",
      "file-restoration"
    ]
    settings = {
      compression = "gzip"
      cleanup     = true
    }
  })
  
  file_permission = "0644"
}

# Output the file paths
output "generated_files" {
  value = {
    example_file = local_file.example.filename
    config_file  = local_file.config.filename
  }
  description = "Paths to generated files"
}
