terraform {
  required_version = ">= 1.0"
}

# Local file resource that generates a file with dummy content
resource "local_file" "example" {
  filename = "${path.module}/generated/example.txt"
  content  = <<-EOT
    This is a dummy file generated by Terraform.
    
    This file demonstrates the preservation problem:
    - Created during Apply
    - Should be preserved for Verify Plan
    - Without preservation, Terraform will try to recreate it
    
    Sample data:
    - Name: Example File
    - Environment: Test
    - Purpose: Demonstrate file preservation
  EOT
  
  file_permission = "0644"
}

# Another local file with JSON content
resource "local_file" "config" {
  filename = "${path.module}/generated/config.json"
  content = jsonencode({
    application = "preserve-files-demo"
    version     = "1.0.0"
    environment = "test"
    features = [
      "tar-archive",
      "s3-upload",
      "file-restoration"
    ]
    settings = {
      compression = "gzip"
      cleanup     = true
    }
  })
  
  file_permission = "0644"
}

# Markdown documentation file
resource "local_file" "readme" {
  filename = "${path.module}/docs/infrastructure/README.md"
  content  = <<-EOT
    # Generated Documentation
    
    ## Overview
    This file is auto-generated by Terraform to demonstrate file preservation.
    
    ## Files in this Archive
    - example.txt: Sample text file
    - config.json: Application configuration
    - README.md: This documentation file
    
    ## Preservation Strategy
    All files in the `generated/` directory are preserved between pipeline stages
    using tar archives stored in S3.
    
    ## Usage
    These files are restored before `terraform plan` verification to prevent
    false drift detection.
  EOT
  
  file_permission = "0644"
}

# Shell script file
resource "local_file" "deploy_script" {
  filename = "${path.module}/scripts/ops/deploy.sh"
  content  = <<-EOT
    #!/bin/bash
    # Auto-generated deployment script
    
    set -e
    
    echo "Starting deployment..."
    echo "Environment: $${ENVIRONMENT:-production}"
    echo "Version: 1.0.0"
    
    # Deployment steps
    echo "✓ Step 1: Validate configuration"
    echo "✓ Step 2: Deploy application"
    echo "✓ Step 3: Run health checks"
    
    echo "Deployment complete!"
  EOT
  
  file_permission = "0755"
}

# CSV data file
resource "local_file" "data_export" {
  filename = "${path.module}/temp/exports/data_2026.csv"
  content  = <<-EOT
    id,name,status,created_at
    1,resource-alpha,active,2026-02-24T10:00:00Z
    2,resource-beta,active,2026-02-24T10:15:00Z
    3,resource-gamma,pending,2026-02-24T10:30:00Z
    4,resource-delta,active,2026-02-24T10:45:00Z
  EOT
  
  file_permission = "0644"
}

# YAML configuration file
resource "local_file" "app_config" {
  filename = "${path.module}/.config/app/settings.yaml"
  content  = <<-EOT
    apiVersion: v1
    kind: Config
    metadata:
      name: preserve-files-demo
      namespace: default
    spec:
      replicas: 3
      image: app:latest
      env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: info
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
  EOT
  
  file_permission = "0644"
}

# HTML file
resource "local_file" "index_html" {
  filename = "${path.module}/build/public/assets/index.html"
  content  = <<-EOT
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Preserve Files Demo</title>
    </head>
    <body>
        <h1>File Preservation Demo</h1>
        <p>This HTML file is generated by Terraform and preserved across pipeline stages.</p>
        <ul>
            <li>Generated at build time</li>
            <li>Preserved in S3</li>
            <li>Restored for verification</li>
        </ul>
    </body>
    </html>
  EOT
  
  file_permission = "0644"
}

# Properties/INI file
resource "local_file" "app_properties" {
  filename = "${path.module}/var/config/spring/application.properties"
  content  = <<-EOT
    # Application Properties
    app.name=preserve-files-demo
    app.version=1.0.0
    app.environment=production
    
    # Database Configuration
    db.host=localhost
    db.port=5432
    db.name=appdb
    
    # Cache Configuration
    cache.enabled=true
    cache.ttl=3600
    
    # Logging
    log.level=INFO
    log.file=/var/log/app.log
  EOT
  
  file_permission = "0644"
}

# Output the file paths
output "generated_files" {
  value = {
    example_file   = local_file.example.filename
    config_file    = local_file.config.filename
    readme_file    = local_file.readme.filename
    script_file    = local_file.deploy_script.filename
    data_file      = local_file.data_export.filename
    yaml_file      = local_file.app_config.filename
    html_file      = local_file.index_html.filename
    properties_file = local_file.app_properties.filename
  }
  description = "Paths to generated files"
}
